title: Test Automation Club
email: rajat@testautomation.club
description: >-
  Quality Assurance
  Test Automation
baseurl: ""
url: ""
github_username:  rajatthareja
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
