title: Test Automation Club
email: rajat@testautomation.club
description: >-
  Quality Assurance
  Test Automation
baseurl: ""
url: ""
twitter_username: RajatThareja
github_username:  rajatthareja

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
