title: Test Automation Club
email: rajat@testautomation.club
description: >-
  Quality Assurance
  Test Automation Club
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
