title: Test Automation Club
author: Rajat Thareja
email: rajat@testautomation.club
description: >-
  Quality Assurance
  Test Automation Club
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
google_analytics: UA-33561933-2
