title: Test Automation
author: Rajat Thareja
email: testautomation@rajatthareja.com
description: >-
  Quality Assurance
  Test Automation
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
google_analytics: UA-33561933-2
